web: newrelic-admin run-program gunicorn --chdir clinks clinks.wsgi --log-file -
worker: cd clinks && celery -A clinks worker --loglevel=info --concurrency=2
scheduler: cd clinks && celery -A clinks beat --loglevel=info