# Generated by Django 4.0.1 on 2022-01-12 14:18

import api.user.managers
import api.utils.Fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', api.utils.Fields.EnumField(choices=[('admin', 'admin'), ('customer', 'customer'), ('company_member', 'company_member'), ('driver', 'driver')], default='admin')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=5, null=True)),
                ('status', api.utils.Fields.EnumField(choices=[('active', 'active'), ('suspended', 'suspended')], default='active')),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('phone_country_code', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', api.utils.Fields.EnumField(choices=[('delete', 'delete'), ('export', 'export')], default='delete')),
                ('request_data', models.JSONField(null=True)),
                ('request_url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
