# Generated by Django 4.0.1 on 2022-02-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.image')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
