# Generated by Django 4.0.1 on 2022-02-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=255)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('default', models.BooleanField(default=False)),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
