# Generated by Django 4.0.1 on 2022-04-01 09:11

import api.utils.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_driver_current_delivery_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identification_status',
            field=api.utils.Fields.EnumField(choices=[('not_requested', 'not_requested'), ('not_required', 'not_required'), ('refused', 'refused'), ('not_provided', 'not_provided'), ('provided', 'provided')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=api.utils.Fields.EnumField(choices=[('rejected_by_venue', 'rejected_by_venue'), ('no_driver_found', 'no_driver_found')], default=None, null=True),
        ),
    ]
