# Generated by Django 3.2.3 on 2022-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220830_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='passcode',
            field=models.PositiveIntegerField(default=5016),
        ),
    ]
