# Generated by Django 4.0.1 on 2022-01-21 15:15

import api.utils.Fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_deleted_at_alter_customer_identification_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('eircode', models.CharField(max_length=255)),
                ('vat_no', models.CharField(max_length=255)),
                ('liquor_license_no', models.CharField(max_length=255)),
                ('stripe_account_id', models.CharField(max_length=255, null=True)),
                ('total_earnings', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('average_delivery_time', models.PositiveIntegerField(default=0)),
                ('total_delivery_time', models.PositiveIntegerField(default=0)),
                ('completed_order_count', models.PositiveIntegerField(default=0)),
                ('total_accept_time', models.PositiveIntegerField(default=0)),
                ('average_accept_time', models.PositiveIntegerField(default=0)),
                ('venue_count', models.PositiveIntegerField(default=0)),
                ('status', api.utils.Fields.EnumField(choices=[('setup_not_completed', 'setup_not_completed'), ('active', 'active'), ('paused', 'paused')], default='setup_not_completed')),
                ('featured_image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_as_featured', to='api.image')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_as_logo', to='api.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', api.utils.Fields.EnumField(choices=[('admin', 'admin'), ('staff', 'staff')], default='staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
