# Generated by Django 4.0.1 on 2022-02-22 10:55

import api.utils.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_verification_status',
            field=api.utils.Fields.EnumField(choices=[('unverified', 'unverified'), ('pending', 'pending'), ('verified', 'verified')], default='unverified'),
        ),
    ]
