# Generated by Django 4.0.1 on 2022-04-06 14:11

import api.utils.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_alltimestat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltimestat',
            name='type',
            field=api.utils.Fields.EnumField(choices=[('company_count', 'company_count'), ('driver_count', 'driver_count'), ('venue_count', 'venue_count'), ('total_earnings', 'total_earnings'), ('total_company_earnings', 'total_company_earnings'), ('total_driver_earnings', 'total_driver_earnings'), ('platform_earnings', 'platform_earnings'), ('sales_count', 'sales_count'), ('delivered_order_count', 'delivered_order_count'), ('cancelled_order_count', 'cancelled_order_count'), ('rejected_order_count', 'rejected_order_count'), ('average_wait_time', 'average_wait_time'), ('customer_count', 'customer_count'), ('total_wait_time', 'total_wait_time'), ('no_driver_found_order_count', 'no_driver_found_order_count'), ('expired_order_count', 'expired_order_count')], default='company_count'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=api.utils.Fields.EnumField(choices=[('rejected_by_venue', 'rejected_by_venue'), ('no_driver_found', 'no_driver_found'), ('expired', 'expired')], default=None, null=True),
        ),
    ]
