# Generated by Django 3.2.3 on 2022-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_venue_service_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='service_fee_percentage',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
    ]
