# Generated by Django 4.0.1 on 2022-01-25 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_company_companymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(max_length=255, null=True)),
                ('line_3', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('country_short', models.CharField(max_length=5)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='api.address'),
        ),
    ]
