# Generated by Django 4.0.1 on 2022-01-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alltimestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDistance',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ends', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
