# Generated by Django 4.0.1 on 2022-01-27 16:40

import api.utils.Fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deliverydistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltimestat',
            name='type',
            field=api.utils.Fields.EnumField(choices=[('company_count', 'company_count'), ('driver_count', 'driver_count'), ('venue_count', 'venue_count')], default='company_count'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('phone_country_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('total_earnings', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('average_delivery_time', models.PositiveIntegerField(default=0)),
                ('total_delivery_time', models.PositiveIntegerField(default=0)),
                ('delivered_order_count', models.PositiveIntegerField(default=0)),
                ('venue_count', models.PositiveIntegerField(default=0)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='api.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', api.utils.Fields.EnumField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], default='sunday')),
                ('order', models.PositiveIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='api.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
