# Generated by Django 4.0.1 on 2022-02-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_company_has_added_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('menu_item_count', models.PositiveIntegerField(default=0)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.image')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
