# Generated by Django 4.0.1 on 2022-03-24 15:34

import api.utils.Fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_order_returned_at_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_looking_for_drivers_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_return_charge_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=api.utils.Fields.EnumField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('missed', 'missed'), ('expired', 'expired')], default='pending'),
        ),
    ]
