# Generated by Django 3.2.3 on 2022-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_companymember_active_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
