# Generated by Django 3.2.3 on 2022-08-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_venue_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_out_at',
            field=models.DateTimeField(null=True),
        ),
    ]
