# Generated by Django 3.2.3 on 2022-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_user_logged_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_known_location_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
