# Generated by Django 3.2.3 on 2022-08-30 14:40

import api.utils.Fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_driver_last_known_location_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_out_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=api.utils.Fields.EnumField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='active'),
        ),
    ]
