# Generated by Django 3.2.3 on 2022-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220912_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery_driver_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='passcode',
            field=models.PositiveIntegerField(),
        ),
    ]
