# Generated by Django 4.0.1 on 2022-01-18 11:48

import api.utils.Fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('banner', models.CharField(max_length=255, null=True)),
                ('original', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', api.utils.Fields.EnumField(choices=[('minimum_age', 'minimum_age')], default='minimum_age')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', api.utils.Fields.EnumField(choices=[('age_card', 'age_card'), ('driver_license', 'driver_license')], default='age_card')),
                ('back', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back', to='api.image')),
                ('front', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='front', to='api.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_customer_id', models.CharField(max_length=255, null=True)),
                ('last_order_at', models.DateTimeField(null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('total_spending', models.PositiveIntegerField(default=0)),
                ('average_spending_per_order', models.PositiveIntegerField(default=0)),
                ('identification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='api.identification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
