# Generated by Django 4.0.1 on 2022-01-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='active_venue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_member', to='api.venue'),
        ),
    ]
