# Generated by Django 4.0.1 on 2022-02-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_currency_menu_menucategory_item_menu_item_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
