# Generated by Django 4.0.1 on 2022-02-22 12:43

import api.utils.Fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_company_stripe_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255)),
                ('result', api.utils.Fields.EnumField(choices=[('processed', 'processed'), ('duplicate', 'duplicate'), ('not_found', 'not_found'), ('not_handled', 'not_handled')], default='processed')),
                ('data', models.JSONField(null=True)),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
