# Generated by Django 4.0.1 on 2022-02-23 10:59

import api.utils.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_webhookevent_company_stripe_charges_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=api.utils.Fields.EnumField(choices=[('minimum_age', 'minimum_age'), ('minimum_order_amount', 'minimum_order_amount')], default='minimum_age'),
        ),
    ]
