# Generated by Django 4.0.1 on 2022-04-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_alltimestat_type_alter_order_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='active_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_members', to='api.venue'),
        ),
    ]
