# Generated by Django 3.2.3 on 2022-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_company_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydistance',
            name='driver_fee',
            field=models.PositiveIntegerField(null=True),
        )
    ]
