# Generated by Django 3.2.3 on 2022-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_payment_delivery_driver_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydistance',
            name='driver_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
