APP_NAME = "api"

MIN_PASSWORD_LENGTH = 6

ADMIN = "admin"
CUSTOMER = "customer"
COMPANY_MEMBER = "company_member"
DRIVER = "driver"

USER_ROLE_ADMIN = ADMIN
USER_ROLE_CUSTOMER = CUSTOMER
USER_ROLE_COMPANY_MEMBER = COMPANY_MEMBER
USER_ROLE_DRIVER = DRIVER

USER_ROLE_DEFAULT = USER_ROLE_CUSTOMER

USER_ROLES = [
    USER_ROLE_ADMIN,
    USER_ROLE_CUSTOMER,
    USER_ROLE_COMPANY_MEMBER,
    USER_ROLE_DRIVER
]

USER_STATUS_ACTIVE = "active"
USER_STATUS_SUSPENDED = "suspended"
USER_STATUS_DELETED = "deleted"

USER_STATUS_DEFAULT = USER_STATUS_ACTIVE

USER_STATUSES = [
    USER_STATUS_ACTIVE,
    USER_STATUS_SUSPENDED,
    USER_STATUS_DELETED
]

USER_AUTH_TOKENS = "tokens"

ADMIN_ROLE_ADMIN = "admin"
ADMIN_ROLE_STAFF = "staff"

ADMIN_ROLE_DEFAULT = ADMIN_ROLE_STAFF

ADMIN_ROLES = [
    ADMIN_ROLE_ADMIN,
    ADMIN_ROLE_STAFF,
]

COMPANY_MEMBER_ROLE_ADMIN = "admin"
COMPANY_MEMBER_ROLE_STAFF = "staff"

COMPANY_MEMBER_ROLE_DEFAULT = COMPANY_MEMBER_ROLE_STAFF

COMPANY_MEMBER_ROLES = [
    COMPANY_MEMBER_ROLE_ADMIN,
    COMPANY_MEMBER_ROLE_STAFF,
]

TIME_PERIOD_TODAY = "today"
TIME_PERIOD_WEEK = "week"
TIME_PERIOD_MONTH = "month"
TIME_PERIOD_YEAR = "year"

DATE_DIFFERENCE_IN_DAYS = "days"
DATE_DIFFERENCE_IN_WEEKS = "weeks"
DATE_DIFFERENCE_IN_YEARS = "years"

LOG_TYPE_DELETE = "delete"
LOG_TYPE_EXPORT = "export"

LOG_TYPES = [LOG_TYPE_DELETE, LOG_TYPE_EXPORT]

IMAGE_UPLOAD_ACCEPTABLE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "svg"]

IDENTIFICATION_TYPE_AGE_CARD = "age_card"
IDENTIFICATION_TYPE_DRIVER_LICENSE = "driver_license"
IDENTIFICATION_TYPE_PASSPORT = "passport"

IDENTIFICATION_TYPES = [
    IDENTIFICATION_TYPE_AGE_CARD,
    IDENTIFICATION_TYPE_DRIVER_LICENSE,
    IDENTIFICATION_TYPE_PASSPORT
]

SETTING_KEY_MINIMUM_AGE = "minimum_age"
SETTING_KEY_MINIMUM_ORDER_AMOUNT = "minimum_order_amount"

SETTING_KEYS = [
    SETTING_KEY_MINIMUM_AGE,
    SETTING_KEY_MINIMUM_ORDER_AMOUNT
]

SETTING_KEYS_INTEGER = [
    SETTING_KEY_MINIMUM_AGE,
    SETTING_KEY_MINIMUM_ORDER_AMOUNT
]

VEHICLE_TYPE_CAR = "car"
VEHICLE_TYPE_SCOOTER = "scooter"
VEHICLE_TYPE_BICYCLE = "bicycle"

VEHICLE_TYPES = [
    VEHICLE_TYPE_CAR,
    VEHICLE_TYPE_SCOOTER,
    VEHICLE_TYPE_BICYCLE
]

COMPANY_STATUS_SETUP_NOT_COMPLETED = "setup_not_completed"
COMPANY_STATUS_ACTIVE = "active"
COMPANY_STATUS_PAUSED = "paused"

COMPANY_STATUS_DEFAULT = COMPANY_STATUS_SETUP_NOT_COMPLETED

COMPANY_STATUSES = [
    COMPANY_STATUS_SETUP_NOT_COMPLETED,
    COMPANY_STATUS_ACTIVE,
    COMPANY_STATUS_PAUSED
]

ALL_TIME_STAT_TYPE_COMPANY_COUNT = "company_count"
ALL_TIME_STAT_TYPE_DRIVER_COUNT = "driver_count"
ALL_TIME_STAT_TYPE_VENUE_COUNT = "venue_count"
ALL_TIME_STAT_TYPE_TOTAL_EARNINGS = "total_earnings"
ALL_TIME_STAT_TYPE_TOTAL_COMPANY_EARNINGS = "total_company_earnings"
ALL_TIME_STAT_TYPE_TOTAL_DRIVER_EARNINGS = "total_driver_earnings"
ALL_TIME_STAT_TYPE_PLATFORM_EARNINGS = "platform_earnings"
ALL_TIME_STAT_TYPE_SALES_COUNT = "sales_count"
ALL_TIME_STAT_TYPE_DELIVERED_ORDER_COUNT = "delivered_order_count"
ALL_TIME_STAT_TYPE_CANCELLED_ORDER_COUNT = "cancelled_order_count"
ALL_TIME_STAT_TYPE_REJECTED_ORDER_COUNT = "rejected_order_count"
ALL_TIME_STAT_TYPE_TOTAL_WAIT_TIME = "total_wait_time"
ALL_TIME_STAT_TYPE_AVERAGE_WAIT_TIME = "average_wait_time"
ALL_TIME_STAT_TYPE_CUSTOMER_COUNT = "customer_count"
ALL_TIME_STAT_NO_DRIVER_FOUND_ORDER_COUNT = "no_driver_found_order_count"
ALL_TIME_STAT_EXPIRED_ORDER_COUNT = "expired_order_count"

ALL_TIME_STAT_TYPES = [
    ALL_TIME_STAT_TYPE_COMPANY_COUNT,
    ALL_TIME_STAT_TYPE_DRIVER_COUNT,
    ALL_TIME_STAT_TYPE_VENUE_COUNT,
    ALL_TIME_STAT_TYPE_TOTAL_EARNINGS,
    ALL_TIME_STAT_TYPE_TOTAL_COMPANY_EARNINGS,
    ALL_TIME_STAT_TYPE_TOTAL_DRIVER_EARNINGS,
    ALL_TIME_STAT_TYPE_PLATFORM_EARNINGS,
    ALL_TIME_STAT_TYPE_SALES_COUNT,
    ALL_TIME_STAT_TYPE_DELIVERED_ORDER_COUNT,
    ALL_TIME_STAT_TYPE_CANCELLED_ORDER_COUNT,
    ALL_TIME_STAT_TYPE_REJECTED_ORDER_COUNT,
    ALL_TIME_STAT_TYPE_AVERAGE_WAIT_TIME,
    ALL_TIME_STAT_TYPE_CUSTOMER_COUNT,
    ALL_TIME_STAT_TYPE_TOTAL_WAIT_TIME,
    ALL_TIME_STAT_NO_DRIVER_FOUND_ORDER_COUNT,
    ALL_TIME_STAT_EXPIRED_ORDER_COUNT
]

DAILY_STAT_TYPE_SALES_COUNT = "sales_count"
DAILY_STAT_TYPE_TOTAL_EARNINGS = "total_earnings"
DAILY_STAT_TYPE_TOTAL_COMPANY_EARNINGS = "total_company_earnings"
DAILY_STAT_TYPE_TOTAL_DRIVER_EARNINGS = "total_driver_earnings"
DAILY_STAT_TYPE_PLATFORM_EARNINGS = "platform_earnings"

DAILY_STAT_TYPES = [
    DAILY_STAT_TYPE_SALES_COUNT,
    DAILY_STAT_TYPE_TOTAL_EARNINGS,
    DAILY_STAT_TYPE_TOTAL_COMPANY_EARNINGS,
    DAILY_STAT_TYPE_TOTAL_DRIVER_EARNINGS,
    DAILY_STAT_TYPE_PLATFORM_EARNINGS
]

DAY_MONDAY = "monday"
DAY_TUESDAY = "tuesday"
DAY_WEDNESDAY = "wednesday"
DAY_THURSDAY = "thursday"
DAY_FRIDAY = "friday"
DAY_SATURDAY = "saturday"
DAY_SUNDAY = "sunday"

DAYS = [
    DAY_SUNDAY,
    DAY_MONDAY,
    DAY_TUESDAY,
    DAY_WEDNESDAY,
    DAY_THURSDAY,
    DAY_FRIDAY,
    DAY_SATURDAY,
]

DAYS_ORDERED = [
    DAY_MONDAY,
    DAY_TUESDAY,
    DAY_WEDNESDAY,
    DAY_THURSDAY,
    DAY_FRIDAY,
    DAY_SATURDAY,
    DAY_SUNDAY
]

ITEM_IMAGE_UPLOAD_ACCEPTABLE_EXTENSIONS = ["image/png", "image/jpg", "image/jpeg"]

STRIPE_VERIFICATION_STATUS_UNVERIFIED = "unverified"
STRIPE_VERIFICATION_STATUS_PENDING = "pending"
STRIPE_VERIFICATION_STATUS_VERIFIED = "verified"

STRIPE_VERIFICATION_STATUSES = [
    STRIPE_VERIFICATION_STATUS_UNVERIFIED,
    STRIPE_VERIFICATION_STATUS_PENDING,
    STRIPE_VERIFICATION_STATUS_VERIFIED
]

WEBHOOK_EVENT_RESULT_PROCESSED = "processed"
WEBHOOK_EVENT_RESULT_DUPLICATE = "duplicate"
WEBHOOK_EVENT_RESULT_NOT_FOUND = "not_found"
WEBHOOK_EVENT_RESULT_NOT_HANDLED = "not_handled"

WEBHOOK_EVENT_RESULTS = [
    WEBHOOK_EVENT_RESULT_PROCESSED,
    WEBHOOK_EVENT_RESULT_DUPLICATE,
    WEBHOOK_EVENT_RESULT_NOT_FOUND,
    WEBHOOK_EVENT_RESULT_NOT_HANDLED
]

ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_LOOKING_FOR_DRIVER = "looking_for_driver"
ORDER_STATUS_ACCEPTED = "accepted"
ORDER_STATUS_REJECTED = "rejected"

ORDER_STATUSES = [
    ORDER_STATUS_PENDING,
    ORDER_STATUS_LOOKING_FOR_DRIVER,
    ORDER_STATUS_ACCEPTED,
    ORDER_STATUS_REJECTED
]

DELIVERY_STATUS_PENDING = "pending"
DELIVERY_STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
DELIVERY_STATUS_FAILED = "failed"
DELIVERY_STATUS_RETURNED = "returned"
DELIVERY_STATUS_DELIVERED = "delivered"

DELIVERY_STATUSES = [
    DELIVERY_STATUS_PENDING,
    DELIVERY_STATUS_OUT_FOR_DELIVERY,
    DELIVERY_STATUS_FAILED,
    DELIVERY_STATUS_RETURNED,
    DELIVERY_STATUS_DELIVERED
]

ORDER_REJECTION_REASON_REJECTED_BY_VENUE = "rejected_by_venue"
ORDER_REJECTION_REASON_NO_DRIVER_FOUND = "no_driver_found"
ORDER_REJECTION_REASON_EXPIRED = "expired"

ORDER_REJECTION_REASONS = [
    ORDER_REJECTION_REASON_REJECTED_BY_VENUE,
    ORDER_REJECTION_REASON_NO_DRIVER_FOUND,
    ORDER_REJECTION_REASON_EXPIRED
]

ORDER_IDENTIFICATION_STATUS_NOT_REQUESTED = "not_requested"
ORDER_IDENTIFICATION_STATUS_NOT_REQUIRED = "not_required"
ORDER_IDENTIFICATION_STATUS_REFUSED = "refused"
ORDER_IDENTIFICATION_STATUS_NOT_PROVIDED = "not_provided"
ORDER_IDENTIFICATION_STATUS_PROVIDED = "provided"

ORDER_IDENTIFICATION_STATUSES = [
    ORDER_IDENTIFICATION_STATUS_NOT_REQUESTED,
    ORDER_IDENTIFICATION_STATUS_NOT_REQUIRED,
    ORDER_IDENTIFICATION_STATUS_REFUSED,
    ORDER_IDENTIFICATION_STATUS_NOT_PROVIDED,
    ORDER_IDENTIFICATION_STATUS_PROVIDED
]


DRIVER_PAYMENT_TYPE_DELIVERY = "delivery"
DRIVER_PAYMENT_TYPE_RETURN = "return"

DRIVER_PAYMENT_TYPES = [
    DRIVER_PAYMENT_TYPE_DELIVERY,
    DRIVER_PAYMENT_TYPE_RETURN
]

DELIVERY_REQUEST_STATUS_PENDING = "pending"
DELIVERY_REQUEST_STATUS_ACCEPTED = "accepted"
DELIVERY_REQUEST_STATUS_REJECTED = "rejected"
DELIVERY_REQUEST_STATUS_MISSED = "missed"
DELIVERY_REQUEST_STATUS_EXPIRED = "expired"

DELIVERY_REQUEST_STATUSES = [
    DELIVERY_REQUEST_STATUS_PENDING,
    DELIVERY_REQUEST_STATUS_ACCEPTED,
    DELIVERY_REQUEST_STATUS_REJECTED,
    DELIVERY_REQUEST_STATUS_MISSED,
    DELIVERY_REQUEST_STATUS_EXPIRED
]

NOTIFICATION_TYPE_ORDER = "order"
NOTIFICATION_TYPE_ORDER_RETURNED = "order_returned"
NOTIFICATION_TYPE_ORDER_DELIVERY_REQUESTS = "delivery_requests"
